from __future__ import annotations

from pathlib import Path

from llmpidtuner.training.config import ServerJobConfig


def render_sbatch(config: ServerJobConfig) -> str:
    workdir_line = f'cd "{config.workdir}"\n' if config.workdir else ""
    setup_block = ""
    if config.setup_commands:
        setup_block = "\n".join(config.setup_commands) + "\n"
    return f"""#!/usr/bin/env bash
# Generated by LLMPIDTuner. Submit on the GPU server with sbatch.
# This script writes logs and artifacts under {config.output_dir}.
#SBATCH --job-name={config.job_name}
#SBATCH --partition={config.partition}
#SBATCH --gres={config.gres}
#SBATCH --cpus-per-task={config.cpus_per_task}
#SBATCH --mem={config.mem}
#SBATCH --time={config.time}
#SBATCH --output={config.output_dir}/{config.job_name}-%j.out
#SBATCH --error={config.output_dir}/{config.job_name}-%j.err

set -euo pipefail

mkdir -p "{config.output_dir}"
{workdir_line}{setup_block}{config.command}
"""


def write_sbatch(config: ServerJobConfig, output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_sbatch(config), encoding="utf-8", newline="\n")
    return path
